server:
  port: 8080
okapi:
  logs:
    sealedPageCap: 20
    sealedPageTtlMs: 5000
    s3:
      endpoint: http://localhost:4566
      region: eu-west-2
      uploadGraceMs: 300000 # 5 min grace period
      bucket: c199eb35-okapi-logs-bucket
      basePrefix: logs
      uploadIntervalMs: 1800000
    dataDir: data-pages
    maxPageBytes: 8388608 # 8 MB by default
    maxDocsPerPage: 1000
    maxPageWindowMs: 3600000 # 1hr
    idxExpiryDuration: 3600000 # 1hr expiry duration for an index file
  swim:
    svcName: okapi-logs
    ips: localhost
    ports: 8080-8081
    k8s:
      svcName: okapi-logs
      pollMillis: 5000
    s3:
      bucket: c199eb35-okapi-logs-bucket