---
cookies:
  secure: true

server:
  port: 8080
okapi:
  ch:
    wal:
      consumeIntervalMs: 200
      batchSize: 64
  nodes:
    nodeIdFile: "./node-id-test"
  cluster:
    clusterId: "test-cluster"
    streamRouterCacheMillis: 1000
    namespace: "okapi-test-server"
  aws:
    region: "eu-west-2"
    endpoint: "http://localhost:4566"
  kafka:
    executors:
      metricsPoolSize: 1
      metricsDelayJitterMs: 100
      metricsDelayInitialMs: 100
      logsPoolSize: 1
      logsDelayJitterMs: 100
      logsDelayInitialMs: 100
      tracesPoolSize: 1
      tracesDelayJitterMs: 100
      tracesDelayInitialMs: 100
    topics:
      logsTopic: "logs-topic"
      metricsTopic: "metrics-topic"
      tracesTopic: "traces-topic"
    consumer:
      logs:
        maxPollRecords: 10
        maxPollIntervalMs: 300000
        bootstrapServers: "localhost:9092"
      metrics:
        maxPollRecords: 10
        maxPollIntervalMs: 300000
        bootstrapServers: "localhost:9092"
      traces:
        maxPollRecords: 10
        maxPollIntervalMs: 300000
        bootstrapServers: "localhost:9092"
  logs:
    expectedInsertions: 1000
    maxPageWindowMs: 600_000
    maxPageBytes: 4096
    bloomFpp: 0.05
    sealedPageCap: 20
    sealedPageTtlMs: 10000
    dataDir: "data-dir"
    idxExpiryDuration: 10_000
    s3Bucket: "s3-logs-bucket"
    s3BasePrefix: "logs"
    s3UploadGraceMs: 0
    bufferPoolFlushEvalMillis: 100
  metrics:
    expectedInsertions: 1000
    maxPageWindowMs: 600_000
    maxPageBytes: 4096
    bloomFpp: 0.05
    sealedPageCap: 20
    sealedPageTtlMs: 10000
    dataDir: "metrics-data-dir"
    idxExpiryDuration: 10_000
    s3Bucket: "s3-data-bucket"
    s3BasePrefix: "metrics"
    s3UploadGraceMs: 0
    bufferPoolFlushEvalMillis: 100
  traces:
    expectedInsertions: 1000
    maxPageWindowMs: 600_000
    maxPageBytes: 4096
    bloomFpp: 0.05
    sealedPageCap: 20
    sealedPageTtlMs: 10000
    dataDir: "traces-data-dir"
    idxExpiryDuration: 10_000
    s3Bucket: "s3-traces-bucket"
    s3BasePrefix: "traces"
    s3UploadGraceMs: 0
    bufferPoolFlushEvalMillis: 100
  query:
    logsQueryProcPoolSize: 1
    metricsQueryProcPoolSize: 1
    tracesQueryProcPoolSize: 1
    logsFanoutPoolSize: 1
    metricsFanoutPoolSize: 1
    tracesFanoutPoolSize: 1
    logsFanoutTimeoutMs: 100
    metricsFanoutTimeoutMs: 100
    tracesFanoutTimeoutMs: 100
  s3:
    upload:
      uploadDelayMs: 100
  zk:
    connectString: "localhost:2181"
    backoffMillis: 1000
    retries: 2
