{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "okapi-ingester.fullname" . }}
  labels:
    {{- include "okapi-ingester.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "okapi-ingester.selectorLabels" . | nindent 6 }}
{{- end }}
